### ISSUE TITLE
⠀

### ISSUE THREAD

**Issue by ceilingtilefan** [RisingGlitch/GIR-Xp-calculator-#1]
![a](https://github.com/RisingGlitch/GIR-Xp-calculator-/assets/104149053/34865fe7-2901-4100-b561-ec159daca193)

**Comment by imnltsa** [comment]
![Screenshot 2024-03-16 174242](https://github.com/RisingGlitch/GIR-Xp-calculator-/assets/95427722/e602a9df-3ff5-44f2-b9d5-fdae54ab9098)

**Comment by RisingGlitch** [comment]
Open source + idiot + GitHub pages is static

**Comment by ceilingtilefan** [comment]
Hi

**Comment by imnltsa** [comment]
> Hi

Skibidi toilet fanum tax
